language: go

services:
- docker

go:
- 1.6

install:
- go get gopkg.in/check.v1
- go get gopkg.in/yaml.v2

script:
- go test -v ./...
- go build -o build/doget github.com/tueftler/doget
- docker build -t tueftler/doget build

after_success:
- sh push.sh $TRAVIS_BRANCH $TRAVIS_TAG
